---
deployment:
  tasks:
    - export ROOTDEPLOYPATH=/home/slbcoop/public_html/
    - export APPDEPLOYPATH=/home/slbcoop/public_html/app
    - /bin/cp -r ./public/assets/ $ROOTDEPLOYPATH
    - /bin/cp -r ./uploads/ $ROOTDEPLOYPATH
    - /bin/cp -r ./app/Controllers/ $APPDEPLOYPATH
    - /bin/cp -r ./app/Models/ $APPDEPLOYPATH
    - /bin/cp -r ./app/Views/ $APPDEPLOYPATH